---
branding: exu
entropy: 160
pythonjobs: 1

instances:
  - id: root
    weight: 80
    critical: true

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localtime
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - grubcfg
    - bootloader
    - umount
  - show:
    - finished
